### ISSUE TITLE
Problem Cloning from git (at 'deploy:update_code').

### ISSUE THREAD

**Issue by zwif** [w-vision/pimcore-deployer#4]
I'm facing a server setup in which I can't access the git server from the server to which I want deploy.

This means the `deploy` task will fail at `deploy:update_code` since it obvisously can't update the code.

Following Idea:
I could add a git remote at the 'deploy-server'. Before deploying I could push manually the latest changes to that server. Then it would be needed to tell the `deploy:update_code` to not clone the files from a git server but reading it from a given directory. 

Is that possible? Or Is there any other workaround for such a situation?

Thanks in advance!

**Comment by dpfaffenbauer** [comment]
yes, read the deployer docs pls:

https://deployer.org/docs/advanced/deploy-strategies.html

**Comment by zwif** [comment]
Thanks, the information, that this repo utilizes [Deployer](https://deployer.org), is IMO quite important. I would highly appreciate if such information would be given in the readme!

**Comment by dpfaffenbauer** [comment]
well, its called pimcore-deployer... so, there is the hint

**Comment by zwif** [comment]
It is a hint if you are, unlike me for example, know about "deployer". I think "explicit is better than implicit". But nevermind it's your repo.

**Comment by aarongerig** [comment]
@zwif No, you‘re totally right. We could be more clear about certain things. I will add this to the README once I find the time.
